using ELibrary.Domain.Entities;

namespace ELibrary.Domain.Interfaces
{
    /// <summary>
    /// Interface for Book Repository.
    /// </summary>
    public interface IBookRepository
    {
        /// <summary>
        /// Gets all books asynchronously.
        /// </summary>
        /// <returns>Collection of books.</returns>
        Task<IEnumerable<Book>> GetAllAsync();

        /// <summary>
        /// Gets book by Id.
        /// </summary>
        /// <param name="id">The identifier</param>
        /// <returns>Book, null in case book does not exists.</returns>
        Task<Book?> GetByIdAsync(Guid id);

        /// <summary>
        /// Gets book by ISBN.
        /// </summary>
        /// <param name="isbn">The book ISBN.</param>
        /// <returns>Book, null in case book does not exists.</returns>
        Task<Book?> GetByISBNAsync(string isbn);

        /// <summary>
        /// Filters books by name, author and isbn.
        /// </summary>
        /// <param name="name">The title of the book.</param>
        /// <param name="author">The name of the author</param>
        /// <param name="isbn">The isbn of the book.</param>
        /// <returns>Collection of books.</returns>
        Task<IEnumerable<Book>> GetFilteredBooksAsync(string? name, string? author, string? isbn);

        /// <summary>
        /// Adds a new book asynchronously.
        /// </summary>
        /// <param name="book">New book</param>
        /// <returns>Added book.</returns>
        /// <remarks>The ID of the book will be auto-generated by EF.</remarks>
        /// <remarks>The RowVersion of the book will be auto-generated by DB trigger - because of SQLIte.</remarks>
        Task<Book> AddAsync(Book book);

        /// <summary>
        /// Updates an existing book.
        /// </summary>
        /// <param name="book">The book entity.</param>
        void Update(Book book);
    }
}
