// <auto-generated />
using System;
using ELibrary.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELibrary.Database.Migrations
{
    [DbContext(typeof(ELibraryDbContext))]
    [Migration("20251125132658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ELibrary.Shared.Entities.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Idate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Udate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c3984d72-57a4-432d-88b1-38290f93450e"),
                            ActualQuantity = 3,
                            Author = "Christopher Ruocchio",
                            ISBN = "9780756419264",
                            Idate = new DateTime(2025, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Empire of Silence",
                            Udate = new DateTime(2025, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc),
                            Year = new DateTime(2018, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("c3984d72-57a4-432d-88b1-38290f93450a"),
                            ActualQuantity = 3,
                            Author = "Christopher Ruocchio",
                            ISBN = "9780756419271",
                            Idate = new DateTime(2025, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Howling Dark",
                            Udate = new DateTime(2025, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc),
                            Year = new DateTime(2019, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("c3984d72-57a4-432d-88b1-38290f93450b"),
                            ActualQuantity = 3,
                            Author = "Christopher Ruocchio",
                            ISBN = "9780756419288",
                            Idate = new DateTime(2025, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demon in white",
                            Udate = new DateTime(2025, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc),
                            Year = new DateTime(2020, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
