// <auto-generated />
using System;
using ELibrary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ELibrary.Infrastructure.Migrations
{
    [DbContext(typeof(ELibraryDbContext))]
    [Migration("20251213132348_InitialPostgreSQL")]
    partial class InitialPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ELibrary.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Year")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasDatabaseName("IX_Book_ISBN");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c3984d72-57a4-432d-88b1-38290f93450e"),
                            ActualQuantity = 3,
                            Author = "Christopher Ruocchio",
                            ISBN = "9780756419264",
                            Name = "Empire of Silence",
                            Year = new DateTime(2018, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("c3984d72-57a4-432d-88b1-38290f93450a"),
                            ActualQuantity = 3,
                            Author = "Christopher Ruocchio",
                            ISBN = "9780756419271",
                            Name = "Howling Dark",
                            Year = new DateTime(2019, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("c3984d72-57a4-432d-88b1-38290f93450b"),
                            ActualQuantity = 3,
                            Author = "Christopher Ruocchio",
                            ISBN = "9780756419288",
                            Name = "Demon in white",
                            Year = new DateTime(2020, 11, 24, 1, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ELibrary.Domain.Entities.BorrowBookRecord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("BookID")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.ToTable("BorrowBookRecords");
                });

            modelBuilder.Entity("ELibrary.Domain.Entities.BorrowBookRecord", b =>
                {
                    b.HasOne("ELibrary.Domain.Entities.Book", "Book")
                        .WithMany("BorrowBookRecords")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ELibrary.Domain.Entities.Book", b =>
                {
                    b.Navigation("BorrowBookRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
